In [5]:
import pandas as pd
import re
import json


input_path = "jty1_.txt"  

with open(input_path, "r", encoding="utf-8") as f:
    text = f.read()

pattern = r"(\/[^\n]+\/(normal|abnormal)\/[^\n]+)\s*[\s\S]*?```json\s*([\s\S]*?)\s*```"
matches = re.findall(pattern, text, re.DOTALL)

rows = []

for match in matches:
    
    path, truth, json_str = match
    
    try:
        data = json.loads(json_str)

        is_scam = bool(data.get("is_scam"))

        if (is_scam and truth == "abnormal") or (not is_scam and truth == "normal"):
            result = True
        else:
            result = False

        rows.append({
            "filename": path.split("/")[-1].strip(),
            "truth": truth,
            "is_scam": data.get("is_scam"),
            "result": result,
            "is_correct": data.get("is_scam"),
            "confidence": data.get("confidence"),
            "risk": data.get("risk"),
            "evidence": "; ".join(data.get("evidence", [])),
            "explanation": data.get("explanation"),            
        })
    except json.JSONDecodeError as e:
        print(f"JSON 파싱 오류 발생 ({path}): {e}")

df = pd.DataFrame(rows, columns=["filename", "truth", "is_scam", "result", "confidence", "risk", "evidence", "explanation"])

output_path = "scam_results.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"CSV 파일 생성 완료: {output_path}")
print(df)

CSV 파일 생성 완료: scam_results.csv
    filename     truth  is_scam  result  confidence  risk  \
0   0011.mp4    normal    False    True        0.80   low
1   0024.mp4    normal    False    True        0.90   low
2   0004.mp4    normal     True   False        0.90  high
3   0001.mp4    normal    False    True        0.90   low
4   0006.mp4    normal     True   False        0.90  high
5   0016.mp4    normal     True   False        0.92   mid
6   0005.mp4    normal     True   False        0.90  high
7   0018.mp4    normal    False    True        0.90   low
8   0023.mp4    normal    False    True        0.90   low
9   0007.mp4    normal    False    True        0.90   low
10  0014.mp4    normal    False    True        0.90   low
11  0021.mp4    normal    False    True        0.90   low
12  0027.mp4    normal    False    True        0.40   low
13  0012.mp4    normal    False    True        0.85   low
14  0010.mp4    normal    False    True        0.90   low
15  0015.mp4    normal     True   False        0.85  high
16  0003.mp4    normal    False    True        0.90   low
17  0002.mp4    normal    False    True        0.90   low
18  0022.mp4    normal    False    True        0.90   low
19  0019.mp4    normal    False    True        0.90   low
20  0008.mp4    normal     True   False        0.92   mid
21  0026.mp4    normal     True   False        0.90  high
22  0000.mp4    normal    False    True        0.90   low
23  0009.mp4    normal    False    True        0.90   low
24  0013.mp4    normal    False    True        0.90   low
25  0020.mp4    normal     True   False        0.90  high
26  0017.mp4    normal     True   False        0.92  high
27  0025.mp4  abnormal     True    True        0.90  high
28  0011.mp4  abnormal     True    True        0.90  high
29  0034.mp4  abnormal     True    True        0.92  high
30  0029.mp4  abnormal     True    True        0.90  high
31  0033.mp4  abnormal     True    True        0.92  high
32  0004.mp4  abnormal    False   False        0.90   low
33  0035.mp4  abnormal     True    True        0.90  high
34  0001.mp4  abnormal     True    True        0.90  high
35  0006.mp4  abnormal     True    True        0.90  high
36  0016.mp4  abnormal     True    True        0.90  high
37  0005.mp4  abnormal     True    True        0.85   mid
38  0018.mp4  abnormal    False   False        0.80   low
39  0007.mp4  abnormal     True    True        0.90   mid
40  0014.mp4  abnormal     True    True        0.92  high
41  0031.mp4  abnormal     True    True        0.80   mid
42  0012.mp4  abnormal    False   False        0.90   low
43  0010.mp4  abnormal     True    True        0.92  high
44  0003.mp4  abnormal     True    True        0.90  high
45  0002.mp4  abnormal     True    True        0.90  high
46  0030.mp4  abnormal     True    True        0.80   mid
47  0008.mp4  abnormal     True    True        0.90  high
48  0026.mp4  abnormal     True    True        0.92  high
49  0032.mp4  abnormal     True    True        0.92  high
50  0000.mp4  abnormal    False   False        0.90   low
51  0009.mp4  abnormal     True    True        0.92  high
52  0013.mp4  abnormal     True    True        0.85  high
53  0017.mp4  abnormal     True    True        0.90  high

                                             evidence  \
0                       Casual setting; Routine tasks
1        Product demonstration; Realistic product use
2   Scammers often use tactics like urgency to pre...
3   Discusses MZ generation's views on part-time j...
4           Manipulative language; Unrealistic claims
5    Unrealistic claims about solving puzzles quickly
6   Food industry worker; Kitchen setting; Request...
7   High-quality food presentation; Focus on reaso...
8            Non-stick coating; Versatile cooking pan
9   Seven-day construction job; Living expenses co...
10                   Refrigerated lemonade; Ice cubes
11
12              Educational content on healthy eating
13                  Humorous and exaggerated dialogue
14  Job at Daiso; Routine tasks like stocking shel...
15                                      T1 Speak x T1
16                Humorous dialogue; Informal setting
17       Job recommendation for INFP personality type
18  Product demonstration without claims of extrao...
19  Routine disposal of liquid nitrogen; Explanati...
20  Difficult working conditions; Long hours; Mani...
21    Unrealistic profit claims; Manipulative tactics
22  Alpa job interview simulation; Fake applicant ...
23  Unusual events sequence; Vending machine opera...
24  No overt fraudulent claims; Normal product dem...
25  The video shows a person in uniform clapping a...
26          Folding the exam paper to conceal answers
27    Unrealistic profit claims; Manipulative tactics
28         Phone scam scenario; Manipulative language
29    Unrealistic profit claims; Manipulative tactics
30    Unrealistic profit claims; Manipulative tactics
31            Large amounts of money promised quickly
32  Various footwear displayed; Clothing store set...
33    Unrealistic profit claims; Manipulative tactics
34   Ohoh Nasda Injung; Lee Won Sun Boto Nasda Dreing
35  Digital wallet account; Online arbitrage scam;...
36              Profit claims; Large amounts of money
37                       Scamming title with '매대행 모집'
38                    Normal social media interaction
39      Coercive behavior; Unethical training methods
40                     Manipulative language; Urgency
41     Promises of high returns; Manipulative tactics
42           No explicit fraudulent claims or tactics
43  Card info required; Question about money retur...
44    Unrealistic profit claims; Manipulative tactics
45    Unrealistic profit claims; Manipulative tactics
46    Unrealistic profit claims; Manipulative tactics
47                                        아이비중고; 장입처제
48  Use of an exaggerated title ('Voice of the Sca...
49    Unrealistic profit claims; Manipulative tactics
50  Customer ordered item before delivery; Promoti...
51  Unrealistic weight loss claims; Manipulative s...
52                                         한체보고; F2구역
53  Profitable information without risk; Unusual p...

                                          explanation
0   The video depicts everyday activities such as ...
1   The video demonstrates the use of a 'CrunchCup...
2   The video utilizes manipulative techniques and...
3   The video provides an analysis of the current ...
4   The video uses manipulative tactics to create ...
5   The video features a person making exaggerated...
6   The video appears to be a scam, as it involves...
7   The video showcases various Korean dishes in d...
8   The video appears to be an advertisement for a...
9   The video details an individual's experience w...
10  The video appears to be demonstrating a proces...
11  The video promotes a certification course for ...
12  The video appears focused solely on discussing...
13  The video depicts a humorous scenario involvin...
14  The video describes working as a part-time emp...
15  The video promotes a product or service associ...
16  The video appears to be a humorous sketch or p...
17  The video appears to be a job advertisement ta...
18  The video focuses on showcasing a product with...
19  The video appears to be an informative piece a...
20  The video describes the difficult and demandin...
21  The video contains text about 'uber taxi' with...
22  The video appears to be a humorous or satirica...
23  The video depicts a series of unusual and poss...
24  The video appears to be a normal demonstration...
25  The video uses tactics to create urgency, impl...
26  The video demonstrates a method for hiding exa...
27  The video contains phrases like 'You can buy g...
28  The video describes a phone scam scenario wher...
29  The video contains numerous exaggerated statem...
30  The video uses exaggerated promises of guarant...
31  The video highlights a fraudulent scheme invol...
32  The video showcases a variety of slippers and ...
33  The video promotes stock investments with exag...
34  The video contains multiple indicators of a sc...
35  The video promotes an online arbitrage scheme,...
36  The video emphasizes making a significant amou...
37  The video contains a scamming element indicate...
38  The video shows a normal conversation on a cha...
39  The video shows a person in white demonstratin...
40  The video contains manipulative language and u...
41  The video contains promises of significant fin...
42  The video focuses on showcasing and reviewing ...
43  The video displays a screen with unusual promp...
44  The video encourages viewers to buy a stock wi...
45  The video contains several indicators of a sca...
46  The video appears to promote a high return on ...
47  The video shows a person performing hypnosis o...
48  The video uses a misleading and sensational ti...
49  The video presents exaggerated and unrealistic...
50  The video appears to be promoting a specific p...
51  The video makes exaggerated and unrealistic cl...
52  The video appears to be promoting a product or...
53  The video contains phrases suggesting that use...

In [6]:
df.groupby(["truth", "result"]).agg({"filename":"count"})

                 filename
truth    result
abnormal False          4
         True          23
normal   False          9
         True          18

In [7]:
df[df['result']==True]

,filename,truth,is_scam,result,confidence,risk,evidence,explanation
0,0011.mp4,normal,False,True,0.80,low,Casual setting; Routine tasks,The video depicts everyday activities such as ...
1,0024.mp4,normal,False,True,0.90,low,Product demonstration; Realistic product use,The video demonstrates the use of a 'CrunchCup...
3,0001.mp4,normal,False,True,0.90,low,Discusses MZ generation's views on part-time j...,The video provides an analysis of the current ...
7,0018.mp4,normal,False,True,0.90,low,High-quality food presentation; Focus on reaso...,The video showcases various Korean dishes in d...
8,0023.mp4,normal,False,True,0.90,low,Non-stick coating; Versatile cooking pan,The video appears to be an advertisement for a...
9,0007.mp4,normal,False,True,0.90,low,Seven-day construction job; Living expenses co...,The video details an individual's experience w...
10,0014.mp4,normal,False,True,0.90,low,Refrigerated lemonade; Ice cubes,The video appears to be demonstrating a proces...
11,0021.mp4,normal,False,True,0.90,low,,The video promotes a certification course for ...
12,0027.mp4,normal,False,True,0.40,low,Educational content on healthy eating,The video appears focused solely on discussing...
13,0012.mp4,normal,False,True,0.85,low,Humorous and exaggerated dialogue,The video depicts a humorous scenario involvin...
14,0010.mp4,normal,False,True,0.90,low,Job at Daiso; Routine tasks like stocking shel...,The video describes working as a part-time emp...
16,0003.mp4,normal,False,True,0.90,low,Humorous dialogue; Informal setting,The video appears to be a humorous sketch or p...
17,0002.mp4,normal,False,True,0.90,low,Job recommendation for INFP personality type,The video appears to be a job advertisement ta...
18,0022.mp4,normal,False,True,0.90,low,Product demonstration without claims of extrao...,The video focuses on showcasing a product with...
19,0019.mp4,normal,False,True,0.90,low,Routine disposal of liquid nitrogen; Explanati...,The video appears to be an informative piece a...
22,0000.mp4,normal,False,True,0.90,low,Alpa job interview simulation; Fake applicant ...,The video appears to be a humorous or satirica...
23,0009.mp4,normal,False,True,0.90,low,Unusual events sequence; Vending machine opera...,The video depicts a series of unusual and poss...
24,0013.mp4,normal,False,True,0.90,low,No overt fraudulent claims; Normal product dem...,The video appears to be a normal demonstration...
27,0025.mp4,abnormal,True,True,0.90,high,Unrealistic profit claims; Manipulative tactics,The video contains phrases like 'You can buy g...
28,0011.mp4,abnormal,True,True,0.90,high,Phone scam scenario; Manipulative language,The video describes a phone scam scenario wher...
29,0034.mp4,abnormal,True,True,0.92,high,Unrealistic profit claims; Manipulative tactics,The video contains numerous exaggerated statem...
30,0029.mp4,abnormal,True,True,0.90,high,Unrealistic profit claims; Manipulative tactics,The video uses exaggerated promises of guarant...
31,0033.mp4,abnormal,True,True,0.92,high,Large amounts of money promised quickly,The video highlights a fraudulent scheme invol...
33,0035.mp4,abnormal,True,True,0.90,high,Unrealistic profit claims; Manipulative tactics,The video promotes stock investments with exag...
34,0001.mp4,abnormal,True,True,0.90,high,Ohoh Nasda Injung; Lee Won Sun Boto Nasda Dreing,The video contains multiple indicators of a sc...
35,0006.mp4,abnormal,True,True,0.90,high,Digital wallet account; Online arbitrage scam;...,"The video promotes an online arbitrage scheme,..."
36,0016.mp4,abnormal,True,True,0.90,high,Profit claims; Large amounts of money,The video emphasizes making a significant amou...
37,0005.mp4,abnormal,True,True,0.85,mid,Scamming title with '매대행 모집',The video contains a scamming element indicate...
39,0007.mp4,abnormal,True,True,0.90,mid,Coercive behavior; Unethical training methods,The video shows a person in white demonstratin...
40,0014.mp4,abnormal,True,True,0.92,high,Manipulative language; Urgency,The video contains manipulative language and u...
41,0031.mp4,abnormal,True,True,0.80,mid,Promises of high returns; Manipulative tactics,The video contains promises of significant fin...
43,0010.mp4,abnormal,True,True,0.92,high,Card info required; Question about money retur...,The video displays a screen with unusual promp...
44,0003.mp4,abnormal,True,True,0.90,high,Unrealistic profit claims; Manipulative tactics,The video encourages viewers to buy a stock wi...
45,0002.mp4,abnormal,True,True,0.90,high,Unrealistic profit claims; Manipulative tactics,The video contains several indicators of a sca...
46,0030.mp4,abnormal,True,True,0.80,mid,Unrealistic profit claims; Manipulative tactics,The video appears to promote a high return on ...
47,0008.mp4,abnormal,True,True,0.90,high,아이비중고; 장입처제,The video shows a person performing hypnosis o...
48,0026.mp4,abnormal,True,True,0.92,high,Use of an exaggerated title ('Voice of the Sca...,The video uses a misleading and sensational ti...
49,0032.mp4,abnormal,True,True,0.92,high,Unrealistic profit claims; Manipulative tactics,The video presents exaggerated and unrealistic...
51,0009.mp4,abnormal,True,True,0.92,high,Unrealistic weight loss claims; Manipulative s...,The video makes exaggerated and unrealistic cl...
52,0013.mp4,abnormal,True,True,0.85,high,한체보고; F2구역,The video appears to be promoting a product or...
53,0017.mp4,abnormal,True,True,0.90,high,Profitable information without risk; Unusual p...,The video contains phrases suggesting that use...

In [8]:
df[df['result']==False]

,filename,truth,is_scam,result,confidence,risk,evidence,explanation
2,0004.mp4,normal,True,False,0.90,high,Scammers often use tactics like urgency to pre...,The video utilizes manipulative techniques and...
4,0006.mp4,normal,True,False,0.90,high,Manipulative language; Unrealistic claims,The video uses manipulative tactics to create ...
5,0016.mp4,normal,True,False,0.92,mid,Unrealistic claims about solving puzzles quickly,The video features a person making exaggerated...
6,0005.mp4,normal,True,False,0.90,high,Food industry worker; Kitchen setting; Request...,"The video appears to be a scam, as it involves..."
15,0015.mp4,normal,True,False,0.85,high,T1 Speak x T1,The video promotes a product or service associ...
20,0008.mp4,normal,True,False,0.92,mid,Difficult working conditions; Long hours; Mani...,The video describes the difficult and demandin...
21,0026.mp4,normal,True,False,0.90,high,Unrealistic profit claims; Manipulative tactics,The video contains text about 'uber taxi' with...
25,0020.mp4,normal,True,False,0.90,high,The video shows a person in uniform clapping a...,"The video uses tactics to create urgency, impl..."
26,0017.mp4,normal,True,False,0.92,high,Folding the exam paper to conceal answers,The video demonstrates a method for hiding exa...
32,0004.mp4,abnormal,False,False,0.90,low,Various footwear displayed; Clothing store set...,The video showcases a variety of slippers and ...
38,0018.mp4,abnormal,False,False,0.80,low,Normal social media interaction,The video shows a normal conversation on a cha...
42,0012.mp4,abnormal,False,False,0.90,low,No explicit fraudulent claims or tactics,The video focuses on showcasing and reviewing ...
50,0000.mp4,abnormal,False,False,0.90,low,Customer ordered item before delivery; Promoti...,The video appears to be promoting a specific p...

In [3]:
import pandas as pd
import re
import json


input_path = "/home/ubuntu/result_20251112_.txt"  

with open(input_path, "r", encoding="utf-8") as f:
    text = f.read()

pattern = r"(/home/ubuntu/video_20251104/(normal|abnormal)/[^ ]+)\s+\[MiniCPM\] output:\s+(\{.*?\})(?=\s+/home|$)"
matches = re.findall(pattern, text, re.DOTALL)

rows = []

for match in matches:
    path, truth, json_str = match
    try:
        data = json.loads(json_str)

        is_scam = bool(data.get("is_scam"))

        if (is_scam and truth == "abnormal") or (not is_scam and truth == "normal"):
            result = True
        else:
            result = False

        rows.append({
            "filename": path.split("/")[-1].strip(),
            "truth": truth,
            "is_scam": data.get("is_scam"),
            "result": result,
            "is_correct": data.get("is_scam"),
            "confidence": data.get("confidence"),
            "risk": data.get("risk"),
            "evidence": "; ".join(data.get("evidence", [])),
            "explanation": data.get("explanation"),            
        })
    except json.JSONDecodeError as e:
        print(f"JSON 파싱 오류 발생 ({path}): {e}")

df = pd.DataFrame(rows, columns=["filename", "truth", "is_scam", "result", "confidence", "risk", "evidence", "explanation"])

output_path = "scam_results.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"CSV 파일 생성 완료: {output_path}")
print(df)

JSON 파싱 오류 발생 (/home/ubuntu/video_20251104/abnormal/0002.mp4
): Invalid control character at: line 6 column 82 (char 158)
CSV 파일 생성 완료: scam_results.csv
    filename     truth  is_scam  result  confidence  risk  \
0   0011.mp4    normal     True   False        0.95  high
1   0024.mp4    normal     True   False        0.95  high
2   0004.mp4    normal     True   False        0.95  high
3   0001.mp4    normal     True   False        0.95  high
4   0006.mp4    normal     True   False        0.95  high
5   0016.mp4    normal     True   False        0.90  high
6   0005.mp4    normal     True   False        0.95  high
7   0018.mp4    normal     True   False        0.95  high
8   0023.mp4    normal    False    True        0.90   low
9   0007.mp4    normal     True   False        0.90  high
10  0014.mp4    normal    False    True        0.90   low
11  0021.mp4    normal     True   False        0.90  high
12  0027.mp4    normal     True   False        0.95  high
13  0012.mp4    normal     True   False        0.95  high
14  0010.mp4    normal     True   False        0.95  high
15  0015.mp4    normal     True   False        0.95  high
16  0003.mp4    normal     True   False        0.90  high
17  0002.mp4    normal     True   False        0.90  high
18  0022.mp4    normal    False    True        0.90   low
19  0019.mp4    normal     True   False        0.95  high
20  0008.mp4    normal     True   False        0.95  high
21  0026.mp4    normal     True   False        0.90  high
22  0000.mp4    normal     True   False        0.95  high
23  0009.mp4    normal     True   False        0.95  high
24  0013.mp4    normal    False    True        0.98   low
25  0020.mp4    normal     True   False        0.95  high
26  0017.mp4    normal     True   False        0.95  high
27  0025.mp4  abnormal     True    True        0.90  high
28  0011.mp4  abnormal     True    True        0.95  high
29  0034.mp4  abnormal     True    True        0.95  high
30  0029.mp4  abnormal     True    True        0.95  high
31  0035.mp4  abnormal     True    True        0.98  high
32  0001.mp4  abnormal     True    True        0.95  high
33  0006.mp4  abnormal     True    True        0.90  high
34  0016.mp4  abnormal     True    True        0.95  high
35  0005.mp4  abnormal     True    True        0.95  high
36  0018.mp4  abnormal     True    True        0.95  high
37  0007.mp4  abnormal     True    True        0.90  high
38  0014.mp4  abnormal     True    True        0.95  high
39  0031.mp4  abnormal     True    True        0.90  high
40  0012.mp4  abnormal     True    True        0.90  high
41  0010.mp4  abnormal     True    True        0.90  high
42  0037.mp4  abnormal     True    True        0.95  high
43  0030.mp4  abnormal     True    True        0.90  high
44  0008.mp4  abnormal     True    True        0.95  high
45  0032.mp4  abnormal     True    True        0.90  high
46  0000.mp4  abnormal     True    True        0.80  high
47  0009.mp4  abnormal     True    True        0.90  high
48  0013.mp4  abnormal     True    True        0.90  high
49  0017.mp4  abnormal     True    True        0.95  high

                                             evidence  \
0   Monetary requests with prepayment, fees, and g...
1   Monetary requests (e.g., 'I will pay, so try i...
2   Monetary requests in the context of a job offe...
3   Monetary solicitation for a part-time job in t...
4   Repeated mentions of financial gains or benefi...
5   Monetary requests for operational fees or trai...
6   Monetary requests for 'Operation fees'; Repeti...
7   Repeated monetary solicitation for prepayment ...
8   Nonstick coating is mentioned.; Demonstration ...
9   Prepayment or fee requests; External channel r...
10  Text mentioning potential scam without explici...
11  Monetary solicitation with phrases like '월 160...
12  External chatroom interaction with a sense of ...
13  Prepayment requests for operational fees; Urge...
14  Monetary requests for 'small investment'.; Ins...
15  Monetary requests (prepayment, fees, etc.); Ur...
16  Prepayment requested (offer 13 billion won); U...
17  Mentions of prepayment, fees, and deposits (in...
18  The video promotes the Dyson Supersonic R hair...
19  Repeated mentions of money or financial transa...
20  Monetary requests (prepayment, fees, etc.); Ex...
21  Request for money in the context of operationa...
22  Monetary requests for prepayment or fees.; Ext...
23  Monetary solicitation with '60,000 won transfe...
24  The video shows the preparation of a banana mi...
25  Monetary requests (plane ticket refund); Urgen...
26  Request for payment in advance, mentioning fee...
27  Repeated mentions of a discount or special off...
28  Monetary Requests: Direct demands for money in...
29  Monetary requests: 'Invest 200,000 KRW and ret...
30  Mentions of monetary requests for prepayment, ...
31  Request for monetary contributions via messagi...
32  Monetary requests mentioned (prepayment, fees,...
33  Monetary solicitation with mention of '50만 원' ...
34  Prepayment or fees mentioned; External channel...
35  Text overlay mentions prepayment and urgency.;...
36  Messages from a chatroom emphasizing urgency w...
37  Repeated emphasis on the scam's purpose throug...
38  Monetary requests (fine of 750,000 won); Urgen...
39  Monetary requests (prepayment, fees, deposits)...
40  Prepayment or gift card requests; Urgency and ...
41  Prepayment requested; Urgency and rules agains...
42  Request for payment or financial transaction; ...
43  Prepayment request mentioned in the video cont...
44  Prepayment or fees requested for participation...
45  Monetary requests: Mentions of prepayment, fee...
46  Prepayment request mentioned in the text overl...
47  Monetary requests in the form of 'prepayment' ...
48  Repeated mentions of prepayment or deposit in ...
49  Monetary requests mentioned (prepayment, fees,...

                                          explanation
0   The video contains multiple scam indicators in...
1   The video contains multiple indicators typical...
2   The video appears to be promoting a scam due t...
3   The video contains strong indicators of a scam...
4   The video contains multiple indicators commonl...
5   The video contains multiple scam indicators, i...
6   The video contains clear indications that it i...
7   The video includes repeated references to urge...
8   The video appears to be an instructional or pr...
9   The video contains multiple indicators that it...
10  The video shows a person making drinks and inc...
11  The video contains strong indicators of a scam...
12  The video shows interactions that suggest mani...
13  The video includes messages from a chatroom th...
14  The video strongly suggests fraudulent activit...
15  The video contains strong indications of a sca...
16  The video includes elements suggesting it is a...
17  The video contains multiple scam indicators in...
18  The content focuses on showcasing a product (D...
19  The video contains strong indicators suggestin...
20  The video contains strong indications typical ...
21  The video demands payment upfront and uses urg...
22  The video demonstrates strong indications of a...
23  The video contains strong indicators typical o...
24  The content is about preparing a dessert, spec...
25  The video contains multiple indicators suggest...
26  The video contains strong indicators typical o...
27  The video exhibits multiple scam indicators in...
28  The video contains elements typical of scams, ...
29  The video contains multiple indicators suggest...
30  The video contains multiple scam indicators su...
31  The video appears designed to manipulate viewe...
32  The video contains clear indications of a scam...
33  The video contains elements typical of a scam ...
34  The video includes messages about monetary req...
35  The video contains text overlays indicating a ...
36  The video includes messages in a chatroom that...
37  The video consistently includes messages from ...
38  The video contains strong indicators of a scam...
39  The video contains messages from a chatroom th...
40  The video includes multiple indicators of frau...
41  The video includes a request for prepayment of...
42  The video suggests a substantial increase in s...
43  The presence of monetary requests, external me...
44  The video contains strong indications of a sca...
45  The video contains messages from a chatroom em...
46  The video contains elements that suggest it is...
47  The video manipulates users into participating...
48  The video contains several scam indicators suc...
49  The video contains clear indicators of a scam ...

In [4]:
df.groupby(["truth", "result"]).agg({"filename":"count"})

                 filename
truth    result
abnormal True          23
normal   False         23
         True           4

In [5]:
import pandas as pd
import re
import json


input_path = "/home/ubuntu/result_20251112_.txt"  

with open(input_path, "r", encoding="utf-8") as f:
    text = f.read()

pattern = r"(/home/ubuntu/video_20251104/(normal|abnormal)/[^ ]+)\s+\[MiniCPM\] output:\s+(\{.*?\})(?=\s+/home|$)"
matches = re.findall(pattern, text, re.DOTALL)

rows = []

for match in matches:
    path, truth, json_str = match
    try:
        data = json.loads(json_str)

        is_scam = bool(data.get("is_scam"))

        if (is_scam and truth == "abnormal") or (not is_scam and truth == "normal"):
            result = True
        else:
            result = False

        rows.append({
            "filename": path.split("/")[-1].strip(),
            "truth": truth,
            "is_scam": data.get("is_scam"),
            "result": result,
            "is_correct": data.get("is_scam"),
            "confidence": data.get("confidence"),
            "risk": data.get("risk"),
            "evidence": "; ".join(data.get("evidence", [])),
            "explanation": data.get("explanation"),            
        })
    except json.JSONDecodeError as e:
        print(f"JSON 파싱 오류 발생 ({path}): {e}")

df = pd.DataFrame(rows, columns=["filename", "truth", "is_scam", "result", "confidence", "risk", "evidence", "explanation"])

output_path = "scam_results.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"CSV 파일 생성 완료: {output_path}")
print(df)

JSON 파싱 오류 발생 (/home/ubuntu/video_20251104/normal/0015.mp4
): Expecting ',' delimiter: line 11 column 185 (char 462)
JSON 파싱 오류 발생 (/home/ubuntu/video_20251104/abnormal/0014.mp4
): Expecting ',' delimiter: line 7 column 19 (char 145)
CSV 파일 생성 완료: scam_results.csv
    filename     truth  is_scam  result  confidence  risk  \
0   0011.mp4    normal    False    True        0.90   low
1   0024.mp4    normal     True   False        0.95  high
2   0004.mp4    normal     True   False        0.95  high
3   0001.mp4    normal     True   False        0.95  high
4   0006.mp4    normal     True   False        0.90  high
5   0016.mp4    normal    False    True        0.80   low
6   0005.mp4    normal    False    True        0.80   low
7   0018.mp4    normal    False    True        0.95   low
8   0023.mp4    normal    False    True        0.95   low
9   0007.mp4    normal    False    True        0.95   low
10  0014.mp4    normal     True   False        0.95  high
11  0021.mp4    normal    False    True        0.60   low
12  0027.mp4    normal    False    True        0.85   low
13  0012.mp4    normal     True   False        0.90  high
14  0010.mp4    normal     True   False        0.95  high
15  0003.mp4    normal     True   False        0.90  high
16  0002.mp4    normal     True   False        0.95  high
17  0022.mp4    normal    False    True        0.98   low
18  0019.mp4    normal    False    True        0.95   low
19  0008.mp4    normal     True   False        0.95  high
20  0026.mp4    normal     True   False        0.95  high
21  0000.mp4    normal     True   False        0.95  high
22  0009.mp4    normal    False    True        0.90   low
23  0013.mp4    normal    False    True        0.95   low
24  0020.mp4    normal     True   False        0.95  high
25  0017.mp4    normal     True   False        0.95  high
26  0025.mp4  abnormal     True    True        0.90  high
27  0011.mp4  abnormal     True    True        0.95  high
28  0034.mp4  abnormal     True    True        0.95  high
29  0029.mp4  abnormal     True    True        0.95  high
30  0033.mp4  abnormal    False   False        0.80   low
31  0004.mp4  abnormal    False   False        0.98   low
32  0035.mp4  abnormal     True    True        0.95  high
33  0001.mp4  abnormal     True    True        0.90  high
34  0006.mp4  abnormal     True    True        0.95  high
35  0016.mp4  abnormal     True    True        0.90  high
36  0005.mp4  abnormal     True    True        0.90  high
37  0018.mp4  abnormal     True    True        0.95  high
38  0007.mp4  abnormal     True    True        0.95  high
39  0031.mp4  abnormal    False   False        0.90   low
40  0012.mp4  abnormal    False   False        0.95   low
41  0010.mp4  abnormal     True    True        0.90  high
42  0037.mp4  abnormal     True    True        0.95  high
43  0002.mp4  abnormal     True    True        0.95  high
44  0030.mp4  abnormal     True    True        0.90  high
45  0008.mp4  abnormal    False   False        0.80   low
46  0026.mp4  abnormal     True    True        0.95  high
47  0032.mp4  abnormal     True    True        0.95  high
48  0000.mp4  abnormal    False   False        0.97   low
49  0009.mp4  abnormal     True    True        0.95  high
50  0013.mp4  abnormal     True    True        0.80  high
51  0017.mp4  abnormal     True    True        0.95  high

                                             evidence  \
0   No monetary requests or solicitations are ment...
1   Promises significant financial returns (e.g., ...
2   Repeated mentions of booking rooms, showing ur...
3   MZ는 왜 이제アルバ리를 안할까?; 2025년 최저임금 인상 확정 10,030원; ...
4   Monetary solicitation: Prepayment, fees, or de...
5   The video shows a person solving a Rubik's cub...
6   No visible monetary solicitations; No external...
7   No prepayment or financial requests are mentio...
8   The video features cooking scenes with Korean ...
9   Video shows a person completing tasks for mone...
10  Monetary requests or claims of guaranteed retu...
11  Promotional content for a job role (Benwon Don...
12  Contains nutritional information for daily cal...
13  Prepayment or deposit request mentioned (as in...
14  Monetary solicitation with phrases like 'Give ...
15  Monetary requests or promises of financial gai...
16  Monetary transaction request (asking for money...
17  The video features a product from Dyson, which...
18               Informational or Educational Purpose
19  Monetary solicitations; External channel promo...
20  Request for prepayment of a portion of the amo...
21  Monetary solicitation (job interview); Urgency...
22  The video features scenes from a bus, indicati...
23  Video features the preparation of a banana mil...
24  Monetary solicitation (asking for a donation);...
25  Mentions of prepayment, fees, and 'only today'...
26  Request for monetary transactions; External ch...
27  Monetary solicitation: 'Account numbers..?' an...
28  Monetary requests (20만 원을 투자하면 약 1억 원이 됩니다); P...
29  Prepayment request for 'D. SAWAR' coins; Urgen...
30  video displays content from KBS news channel; ...
31  Shelves of various sandals in different colors...
32  Monetary requests: Prepayment, fees, deposits,...
33  Monetary requests mentioned (prepayment, fees,...
34  Request for a large sum of money upfront (5 mi...
35  Monetary solicitation: 'Let's make money toget...
36  Text overlay indicating prepayment and high re...
37  External channel promotion: Display of a Teleg...
38  Mentions of financial gain and scam techniques...
39  No monetary requests or promises of high retur...
40  The video shows a person holding up jeans and ...
41  Monetary request for card information; Urgency...
42  Monetary requests: Prepayment, fees, deposits,...
43  Request for monetary transactions (asking to s...
44  Request for money; Claim of scam and fraud edu...
45  Large group of people seated on the floor; Ind...
46  Monetary solicitation; External channel redire...
47  Monetary solicitation; External channel redire...
48  The video does not contain any explicit moneta...
49  Monetary Requests: Mentions of prepayment, fee...
50  Presence of prepayment and VIP floor booking i...
51  Monetary Requests: Mentions of prepayment, fee...

                                          explanation
0   The content focuses on daily activities and pe...
1   The video appears to be a scam due to the emph...
2   The video exhibits strong indicators typical o...
3   The video contains strong indicators of a scam...
4   The video includes strong indicators of a scam...
5   The content appears to be about demonstrating ...
6   The video lacks clear indicators of fraud such...
7   The video seems non-fraudulent as it primarily...
8   The content is about demonstrating the versati...
9   The content does not display clear indicators ...
10  The video contains indicators suggesting a sca...
11  The video promotes career development in the f...
12  The video provides educational content about d...
13  The video includes indicators suggesting fraud...
14  The video contains strong indications typical ...
15  The video contains strong indicators that it i...
16  The video shows elements typical of scams: req...
17  The content focuses on showcasing the design a...
18  The video primarily serves an informational an...
19  The video promotes a job opportunity that appe...
20  The video contains multiple scam indicators, s...
21  The video appears to be a scam as it involves ...
22  The content primarily shows day-to-day activit...
23  The video is focused on demonstrating how to m...
24  The video includes strong indicators of a scam...
25  The video promotes a method for manipulating e...
26  The video includes elements commonly associate...
27  The video contains multiple scam indicators, s...
28  The video contains several strong indicators o...
29  The video contains strong indicators typical o...
30  The content appears to be a standard informati...
31                                               None
32  The video displays stock charts with heavy mon...
33  The video contains several indicators that it ...
34  The video displays strong indicators of a fina...
35  The video contains strong indicators of a scam...
36  The video contains strong indicators of a scam...
37  The video is classified as potentially fraudul...
38  The video contains strong indicators typical o...
39  The video lacks explicit scam indicators such ...
40  The presence of detailed discussions about den...
41  The video shows a screen that requests persona...
42  The video promotes a stock investment opportun...
43  The video displays characteristics typical of ...
44  The video features indicators commonly associa...
45  The video depicts a scene where individuals ar...
46  The video contains strong indicators typical o...
47  The video includes multiple indicators of a po...
48                                               None
49  The video contains strong indicators typical o...
50  The video contains indications that suggest it...
51  The video contains indicators typical of scams...

In [6]:
df.groupby(["truth", "result"]).agg({"filename":"count"})

                 filename
truth    result
abnormal False          6
         True          20
normal   False         14
         True          12